
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kisndnwlvephihwahbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpc25kbndsdmVwaGlod2FoYnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDg4MDYsImV4cCI6MjA1Mjc4NDgwNn0.3FAIqKH2atMyYZ_BxS9SiBAfjwvC_KZZuq2V1z-2Ryc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
